import type { 
  ClassMember, 
  LearningPath, 
  AssignmentItem, 
  QuizItem, 
  MaterialItem, 
  NotificationItem 
} from '../types/myCourse';

// Mock class members data
export const MOCK_CLASS_MEMBERS: ClassMember[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@email.com',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    role: 'teacher',
    joinedAt: '2024-01-15',
    status: 'active',
  },
  {
    id: '2',
    name: 'Emily Johnson',
    email: 'emily.johnson@email.com',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    role: 'student',
    joinedAt: '2024-02-01',
    status: 'active',
    progress: 75,
  },
  {
    id: '3',
    name: 'Michael Brown',
    email: 'michael.brown@email.com',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    role: 'student',
    joinedAt: '2024-02-05',
    status: 'active',
    progress: 60,
  },
  {
    id: '4',
    name: 'Sarah Davis',
    email: 'sarah.davis@email.com',
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    role: 'student',
    joinedAt: '2024-02-10',
    status: 'active',
    progress: 90,
  },
  {
    id: '5',
    name: 'David Wilson',
    email: 'david.wilson@email.com',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    role: 'assistant',
    joinedAt: '2024-01-20',
    status: 'active',
  },
  {
    id: '6',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@email.com',
    avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    role: 'student',
    joinedAt: '2024-02-15',
    status: 'inactive',
    progress: 30,
  },
];

// Mock learning path data
export const MOCK_LEARNING_PATH: LearningPath[] = [
  {
    id: '1',
    title: 'Introduction to Web Development',
    description: 'Learn the basics of HTML, CSS, and JavaScript',
    order: 1,
    duration: '2 hours',
    status: 'completed',
    lessons: [
      { id: '1-1', title: 'What is Web Development?', type: 'video', duration: '15 min', completed: true },
      { id: '1-2', title: 'Setting Up Your Environment', type: 'reading', duration: '10 min', completed: true },
      { id: '1-3', title: 'Your First HTML Page', type: 'video', duration: '20 min', completed: true },
      { id: '1-4', title: 'Module Quiz', type: 'quiz', duration: '15 min', completed: true },
    ],
  },
  {
    id: '2',
    title: 'CSS Fundamentals',
    description: 'Master the art of styling web pages',
    order: 2,
    duration: '3 hours',
    status: 'in-progress',
    lessons: [
      { id: '2-1', title: 'CSS Selectors', type: 'video', duration: '25 min', completed: true },
      { id: '2-2', title: 'Box Model', type: 'video', duration: '20 min', completed: true },
      { id: '2-3', title: 'Flexbox Layout', type: 'video', duration: '30 min', completed: false },
      { id: '2-4', title: 'CSS Grid', type: 'video', duration: '30 min', completed: false },
      { id: '2-5', title: 'Practice Assignment', type: 'assignment', duration: '45 min', completed: false },
    ],
  },
  {
    id: '3',
    title: 'JavaScript Basics',
    description: 'Add interactivity to your websites',
    order: 3,
    duration: '4 hours',
    status: 'available',
    lessons: [
      { id: '3-1', title: 'Variables and Data Types', type: 'video', duration: '25 min', completed: false },
      { id: '3-2', title: 'Functions and Scope', type: 'video', duration: '30 min', completed: false },
      { id: '3-3', title: 'DOM Manipulation', type: 'video', duration: '35 min', completed: false },
      { id: '3-4', title: 'Events and Handlers', type: 'video', duration: '30 min', completed: false },
      { id: '3-5', title: 'Final Project', type: 'assignment', duration: '60 min', completed: false },
    ],
  },
  {
    id: '4',
    title: 'React Fundamentals',
    description: 'Build modern user interfaces with React',
    order: 4,
    duration: '5 hours',
    status: 'locked',
    lessons: [
      { id: '4-1', title: 'Introduction to React', type: 'video', duration: '20 min', completed: false },
      { id: '4-2', title: 'Components and Props', type: 'video', duration: '30 min', completed: false },
      { id: '4-3', title: 'State and Lifecycle', type: 'video', duration: '35 min', completed: false },
      { id: '4-4', title: 'Hooks Deep Dive', type: 'video', duration: '40 min', completed: false },
    ],
  },
];

// Mock assignments data
export const MOCK_ASSIGNMENTS: AssignmentItem[] = [
  {
    id: '1',
    title: 'Build a Personal Portfolio',
    description: 'Create a responsive personal portfolio website using HTML and CSS',
    dueDate: '2024-12-15',
    status: 'pending',
    maxGrade: 100,
    attachments: ['portfolio-requirements.pdf'],
  },
  {
    id: '2',
    title: 'JavaScript Calculator',
    description: 'Build a functional calculator using vanilla JavaScript',
    dueDate: '2024-12-10',
    status: 'submitted',
    submittedAt: '2024-12-08',
    maxGrade: 100,
    attachments: ['calculator-specs.pdf'],
  },
  {
    id: '3',
    title: 'CSS Flexbox Layout',
    description: 'Recreate the given design using CSS Flexbox',
    dueDate: '2024-12-01',
    status: 'graded',
    grade: 95,
    maxGrade: 100,
    attachments: ['flexbox-design.png'],
    feedback: 'Excellent work! Great attention to detail.',
  },
  {
    id: '4',
    title: 'Responsive Navigation',
    description: 'Create a mobile-responsive navigation menu',
    dueDate: '2024-11-25',
    status: 'overdue',
    maxGrade: 100,
    attachments: ['nav-requirements.pdf'],
  },
];

// Mock quizzes data
export const MOCK_QUIZZES: QuizItem[] = [
  {
    id: '1',
    title: 'HTML Fundamentals Quiz',
    description: 'Test your knowledge of HTML basics',
    duration: 15,
    questions: 20,
    attempts: 2,
    maxAttempts: 3,
    bestScore: 85,
    status: 'completed',
  },
  {
    id: '2',
    title: 'CSS Selectors Quiz',
    description: 'Master CSS selector knowledge',
    duration: 20,
    questions: 25,
    attempts: 1,
    maxAttempts: 3,
    bestScore: 72,
    status: 'completed',
  },
  {
    id: '3',
    title: 'JavaScript Basics Quiz',
    description: 'Test your JavaScript fundamentals',
    duration: 30,
    questions: 30,
    attempts: 0,
    maxAttempts: 3,
    status: 'not-started',
    dueDate: '2024-12-20',
  },
  {
    id: '4',
    title: 'React Components Quiz',
    description: 'Understanding React component patterns',
    duration: 25,
    questions: 20,
    attempts: 0,
    maxAttempts: 2,
    status: 'not-started',
    dueDate: '2024-12-25',
  },
];

// Mock materials data
export const MOCK_MATERIALS: MaterialItem[] = [
  {
    id: '1',
    title: 'Course Syllabus',
    type: 'pdf',
    size: '2.5 MB',
    uploadedAt: '2024-01-15',
    downloadUrl: '/materials/syllabus.pdf',
    description: 'Complete course outline and objectives',
  },
  {
    id: '2',
    title: 'HTML Cheat Sheet',
    type: 'pdf',
    size: '1.2 MB',
    uploadedAt: '2024-02-01',
    downloadUrl: '/materials/html-cheat-sheet.pdf',
    description: 'Quick reference guide for HTML tags',
  },
  {
    id: '3',
    title: 'CSS Properties Reference',
    type: 'document',
    size: '3.8 MB',
    uploadedAt: '2024-02-10',
    downloadUrl: '/materials/css-reference.docx',
    description: 'Comprehensive CSS properties documentation',
  },
  {
    id: '4',
    title: 'JavaScript ES6 Tutorial',
    type: 'video',
    size: '150 MB',
    uploadedAt: '2024-02-15',
    downloadUrl: '/materials/es6-tutorial.mp4',
    description: 'Video tutorial on ES6 features',
  },
  {
    id: '5',
    title: 'React Documentation',
    type: 'link',
    uploadedAt: '2024-02-20',
    downloadUrl: 'https://reactjs.org/docs',
    description: 'Official React documentation',
  },
  {
    id: '6',
    title: 'Project Assets',
    type: 'image',
    size: '25 MB',
    uploadedAt: '2024-02-25',
    downloadUrl: '/materials/project-assets.zip',
    description: 'Images and icons for projects',
  },
];

// Mock notifications data
export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: '1',
    title: 'New Assignment Posted',
    content: 'A new assignment "Build a Personal Portfolio" has been posted. Due date: December 15, 2024.',
    type: 'assignment',
    createdAt: '2024-12-01T10:00:00',
    isRead: false,
    author: {
      name: 'John Smith',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
  },
  {
    id: '2',
    title: 'Grade Posted',
    content: 'Your grade for "CSS Flexbox Layout" assignment has been posted. You scored 95/100.',
    type: 'grade',
    createdAt: '2024-11-28T14:30:00',
    isRead: true,
    author: {
      name: 'John Smith',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
  },
  {
    id: '3',
    title: 'Class Schedule Change',
    content: 'The class scheduled for December 5th has been moved to December 6th at 3:00 PM.',
    type: 'announcement',
    createdAt: '2024-11-25T09:00:00',
    isRead: true,
    author: {
      name: 'John Smith',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
  },
  {
    id: '4',
    title: 'Quiz Reminder',
    content: 'Don\'t forget! The JavaScript Basics Quiz is due on December 20, 2024.',
    type: 'reminder',
    createdAt: '2024-11-20T08:00:00',
    isRead: false,
    author: {
      name: 'System',
      avatar: '',
    },
  },
  {
    id: '5',
    title: 'Welcome to the Course!',
    content: 'Welcome to Web Development Fundamentals! We\'re excited to have you here.',
    type: 'general',
    createdAt: '2024-01-15T09:00:00',
    isRead: true,
    author: {
      name: 'John Smith',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
  },
];

// Mock courses list
export const MOCK_MY_COURSES = [
  {
    key: '1',
    id: 1,
    image: 'https://img.freepik.com/free-photo/programming-background-with-person-working-with-codes-computer_23-2150010125.jpg',
    title: 'The Complete Web Developer Course 2.0',
    teacher: 'John Smith',
    status: 'learning',
    lessons: '12/25',
    progress: 48,
    category: 'Web Development',
    nextLesson: 'Flexbox Layout',
    nextLessonTime: 'Tomorrow at 10:00 AM',
  },
  {
    key: '2',
    id: 2,
    image: 'https://img.freepik.com/free-photo/digital-marketing-with-icons-business-people_53876-94833.jpg',
    title: 'Digital Marketing Masterclass',
    teacher: 'Sarah Wilson',
    status: 'completed',
    lessons: '18/18',
    progress: 100,
    category: 'Marketing',
    completedDate: '2024-11-15',
  },
  {
    key: '3',
    id: 3,
    image: 'https://img.freepik.com/free-photo/graphic-designer-working-tablet_23-2147652935.jpg',
    title: 'Graphic Design Masterclass',
    teacher: 'Mike Johnson',
    status: 'pending',
    lessons: '0/30',
    progress: 0,
    category: 'Design',
    startDate: '2024-12-15',
  },
  {
    key: '4',
    id: 4,
    image: 'https://img.freepik.com/free-photo/ai-technology-microchip-background-digital-transformation-concept_53876-124669.jpg',
    title: 'Machine Learning Fundamentals',
    teacher: 'Dr. Emily Chen',
    status: 'learning',
    lessons: '8/20',
    progress: 40,
    category: 'AI & ML',
    nextLesson: 'Neural Networks',
    nextLessonTime: 'Dec 5 at 2:00 PM',
  },
];
