import type { ScheduleEvent } from '../types/schedule';

export const MOCK_SCHEDULE_EVENTS: ScheduleEvent[] = [
  {
    id: '1',
    title: 'Web Development Class',
    courseId: '1',
    courseName: 'The Complete Web Developer Course',
    type: 'class',
    date: '2024-12-08',
    startTime: '08:00',
    endTime: '10:00',
    description: 'HTML & CSS fundamentals - Building layouts',
    instructor: 'John Smith',
    location: 'Online - Zoom',
    status: 'upcoming',
    color: '#3B82F6',
  },
  {
    id: '2',
    title: 'React Basics Session',
    courseId: '1',
    courseName: 'The Complete Web Developer Course',
    type: 'class',
    date: '2024-12-10',
    startTime: '10:00',
    endTime: '12:00',
    description: 'Introduction to React components and props',
    instructor: 'John Smith',
    location: 'Online - Zoom',
    status: 'upcoming',
    color: '#3B82F6',
  },
  {
    id: '3',
    title: 'Portfolio Assignment Due',
    courseId: '1',
    courseName: 'The Complete Web Developer Course',
    type: 'deadline',
    date: '2024-12-15',
    startTime: '23:59',
    endTime: '23:59',
    description: 'Submit your personal portfolio project',
    status: 'upcoming',
    color: '#EF4444',
  },
  {
    id: '4',
    title: 'UI/UX Design Workshop',
    courseId: '3',
    courseName: 'Graphic Design Masterclass',
    type: 'class',
    date: '2024-12-09',
    startTime: '14:00',
    endTime: '16:00',
    description: 'Figma basics and design principles',
    instructor: 'Mike Johnson',
    location: 'Online - Google Meet',
    status: 'upcoming',
    color: '#8B5CF6',
  },
  {
    id: '5',
    title: 'JavaScript Quiz',
    courseId: '1',
    courseName: 'The Complete Web Developer Course',
    type: 'quiz',
    date: '2024-12-20',
    startTime: '09:00',
    endTime: '10:00',
    description: 'Test your JavaScript fundamentals knowledge',
    status: 'upcoming',
    color: '#10B981',
  },
  {
    id: '6',
    title: 'Machine Learning Intro',
    courseId: '4',
    courseName: 'Machine Learning Fundamentals',
    type: 'class',
    date: '2024-12-05',
    startTime: '14:00',
    endTime: '16:00',
    description: 'Introduction to Neural Networks',
    instructor: 'Dr. Emily Chen',
    location: 'Online - Zoom',
    status: 'upcoming',
    color: '#F59E0B',
  },
  {
    id: '7',
    title: 'One-on-One Mentoring',
    courseId: '1',
    courseName: 'The Complete Web Developer Course',
    type: 'meeting',
    date: '2024-12-12',
    startTime: '15:00',
    endTime: '15:30',
    description: 'Progress review and Q&A session',
    instructor: 'John Smith',
    location: 'Online - Zoom',
    status: 'upcoming',
    color: '#EC4899',
  },
  {
    id: '8',
    title: 'CSS Flexbox Assignment',
    courseId: '1',
    courseName: 'The Complete Web Developer Course',
    type: 'assignment',
    date: '2024-12-18',
    startTime: '23:59',
    endTime: '23:59',
    description: 'Create a responsive layout using Flexbox',
    status: 'upcoming',
    color: '#F97316',
  },
];

export const EVENT_TYPE_CONFIG = {
  class: { label: 'Class', color: '#3B82F6', bgColor: 'bg-blue-50', textColor: 'text-blue-600', borderColor: 'border-blue-200' },
  assignment: { label: 'Assignment', color: '#F97316', bgColor: 'bg-orange-50', textColor: 'text-orange-600', borderColor: 'border-orange-200' },
  quiz: { label: 'Quiz', color: '#10B981', bgColor: 'bg-green-50', textColor: 'text-green-600', borderColor: 'border-green-200' },
  meeting: { label: 'Meeting', color: '#EC4899', bgColor: 'bg-pink-50', textColor: 'text-pink-600', borderColor: 'border-pink-200' },
  deadline: { label: 'Deadline', color: '#EF4444', bgColor: 'bg-red-50', textColor: 'text-red-600', borderColor: 'border-red-200' },
};
